### ISSUE TITLE
[Progress Tracker] Support for Manual Trips and more stations

### ISSUE THREAD

**Issue by MrKrisKrisu** [Traewelling/traewelling#2411]
This pinned issue will document the progress of the project for Träwelling supporting manual trips and other stations
then known by "Deutsche Bahn HAFAS".
The goal is to change Träwelling this way, we are able to support multiple data sources.
To achieve this we want to use data from [Wikidata](https://www.wikimedia.de/projects/wikidata/) and the IFOPT ([Wikipedia](https://en.wikipedia.org/wiki/Identification_of_Fixed_Objects_in_Public_Transport), [OpenStreetMap Wiki](https://wiki.openstreetmap.org/wiki/DE:Key:ref:IFOPT)) as a unique identifier for stations.

> [!IMPORTANT]  
> Dear API Consumers, in the next few weeks and months we will change some endpoints and the data structure of Träwelling.
> Please be aware of this and check the [changelog](https://github.com/Traewelling/traewelling/blob/develop/API_CHANGELOG.md) regularly as there will be breaking changes.
> We try to keep the impact as low as possible and add backwards compatibility where it is possible.

> [!TIP]
> If you enjoy maintaining data, Wikidata is a suitable platform to save structured data so that a large number of projects can benefit from it under a free license.
> Many train stations, bus stops and more do not exist there or have not stored any associated IDs (IBNR, IFOPT/DHID, ...). Wikidata lives from people who volunteer data.
> If you are interested in helping to improve the data quality of public transport stations, you can have a look at train stations in your area and add missing information.
> Have a look at [Karlsruhe Main Station (Q688541)](https://www.wikidata.org/wiki/Q688541) as an example.

### Manual trip creation

- [x] Let `closed beta` users create trips manually with existing station data
    - [x] Check if there are any error on frontend, backend and API side
    - [x] Move trip creation from `closed beta` to `experimental features` (#2427 )

### Station support

- [x] Add Columns for storing the Wikidata ID in the `stations` table (#2389)
- [x] Link local station entity with Wikidata entity and fetch raw data for testing (#2389)
- [x] Add Columns for storing the IFOPT ID in the `stations` table (every segment of the IFOPT ID should be stored in a
  separate column!) (#2413)
- [x] Fetch IFOPT from Wikidata if available
- [x] Let users create stations from Wikidata Entities

### Detach from using the IBNR as a unique identifier

- [x] Change all API endpoints which are currently using the IBNR or the Name of a station as query to use the
  Träwelling ID
    - [x] `GET /trains/station/{name}/departures` (#2410)
    - [x] `GET /trains/station/{name}/home` (#2412)
- [x] IBNR
    - [x] Add station id to hafas_trips (#2443)
    - [x] Remove station ibnr from hafas_trips (#2580)
    - [x] Make ibnr nullable (#2579)
    - [x] Update existing ibnr-less stations to null (there are some starting with 99999... in the database)

**Comment by DRSchlaubi** [comment]
What is currently blocking us from allowing users to create their own stations?

I assume it's not just the actual endpoint creating stations but some validation for user created stations both at the time of creation and when using them, since there is a difference of wiki data provided stations and hafas provided stations?

**Comment by MrKrisKrisu** [comment]
> What is currently blocking us from allowing users to create their own stations?
> 
> I assume it's not just the actual endpoint creating stations but some validation for user created stations both at the time of creation and when using them, since there is a difference of wiki data provided stations and hafas provided stations?

Technically, this would not be a problem. You would just have to think about how to validate the data and also avoid duplicates and data waste in general.

**Comment by ChillLP** [comment]
as stupid as it sounds, maybe make it a request form like events are?
and if similar formulations are in place ( Like Köln Messe/Deutz [KKDZ] and Köln Messe/Deutz Tief [KKDT]) check them against each other like usernames are checked (hi, not a sodtware programmer typing this can you tell)
